import { db, menuCategoriesTable, dishesTable, productCategoriesTable, productsTable, eventsTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { logger } from "./lib/logger";

export async function seedDatabase() {
  try {
    const existingCategories = await db.select().from(menuCategoriesTable).limit(1);
    if (existingCategories.length > 0) {
      logger.info("Database already seeded, skipping");
      return;
    }

    logger.info("Seeding database...");

    // Menu Categories
    const categories = await db.insert(menuCategoriesTable).values([
      { name: "Antipasti", slug: "antipasti", icon: "🍞", sortOrder: 1 },
      { name: "Primi", slug: "primi", icon: "🍝", sortOrder: 2 },
      { name: "Secondi", slug: "secondi", icon: "🍖", sortOrder: 3 },
      { name: "Contorni", slug: "contorni", icon: "🥗", sortOrder: 4 },
      { name: "Dolci", slug: "dolci", icon: "🍰", sortOrder: 5 },
      { name: "Bevande", slug: "bevande", icon: "🥤", sortOrder: 6 },
    ]).returning();

    const catMap: Record<string, number> = {};
    for (const c of categories) catMap[c.slug] = c.id;

    // Dishes
    await db.insert(dishesTable).values([
      {
        name: "Bruschetta Be Kind",
        description: "Pane tostato con pomodorini freschi, basilico profumato e olio extravergine di oliva delle Marche",
        price: 7.00,
        categoryId: catMap["antipasti"],
        ingredients: ["Pane di casa", "Pomodorini", "Basilico fresco", "Olio EVO", "Aglio", "Sale marino"],
        allergens: ["glutine"],
        dietaryTags: ["Vegan", "Vegetariano"],
        isAvailable: true,
        isFeatured: true,
      },
      {
        name: "Tagliere Misto",
        description: "Selezione di salumi e formaggi locali accompagnati da miele artigianale e mostarda di frutta",
        price: 14.00,
        categoryId: catMap["antipasti"],
        ingredients: ["Salumi misti", "Formaggi stagionati", "Miele millefiori", "Mostarda di frutta", "Grissini"],
        allergens: ["glutine", "lattosio"],
        dietaryTags: [],
        isAvailable: true,
        isFeatured: false,
      },
      {
        name: "Hummus della Casa",
        description: "Vellutata crema di ceci con paprika affumicata, prezzemolo fresco e pane pita caldo",
        price: 8.50,
        categoryId: catMap["antipasti"],
        ingredients: ["Ceci", "Tahini", "Succo di limone", "Paprika affumicata", "Olio EVO", "Pane pita"],
        allergens: ["glutine", "sesamo"],
        dietaryTags: ["Vegan", "Vegetariano"],
        isAvailable: true,
        isFeatured: false,
      },
      {
        name: "Paccheri alla Norma",
        description: "Paccheri artigianali con melanzane grigliate, pomodoro San Marzano, ricotta salata e foglie di basilico",
        price: 13.00,
        categoryId: catMap["primi"],
        ingredients: ["Paccheri di Gragnano", "Melanzane", "Pomodoro San Marzano", "Ricotta salata", "Basilico", "Aglio"],
        allergens: ["glutine", "lattosio"],
        dietaryTags: ["Vegetariano"],
        isAvailable: true,
        isFeatured: true,
      },
      {
        name: "Risotto ai Funghi Porcini",
        description: "Riso Carnaroli mantecato con porcini freschi di stagione, burro di malga e parmigiano Reggiano 24 mesi",
        price: 15.00,
        categoryId: catMap["primi"],
        ingredients: ["Riso Carnaroli", "Funghi porcini freschi", "Burro di malga", "Parmigiano 24 mesi", "Vino bianco", "Brodo vegetale"],
        allergens: ["lattosio"],
        dietaryTags: ["Vegetariano", "Senza Glutine"],
        isAvailable: true,
        isFeatured: true,
      },
      {
        name: "Spaghetti allo Scoglio",
        description: "Spaghetti trafilati al bronzo con frutti di mare misti dell'Adriatico, pomodorino datterino e prezzemolo fresco",
        price: 16.00,
        categoryId: catMap["primi"],
        ingredients: ["Spaghetti", "Vongole", "Cozze", "Gamberi", "Calamari", "Pomodorino", "Prezzemolo", "Aglio", "Vino bianco"],
        allergens: ["glutine", "molluschi", "crostacei"],
        dietaryTags: [],
        isAvailable: true,
        isFeatured: false,
      },
      {
        name: "Filetto di Branzino",
        description: "Branzino selvaggio al forno su letto di patate croccanti con verdure di stagione e salsa al limone",
        price: 18.00,
        categoryId: catMap["secondi"],
        ingredients: ["Branzino selvaggio", "Patate", "Verdure di stagione", "Limone", "Erbe aromatiche", "Olio EVO"],
        allergens: ["pesce"],
        dietaryTags: ["Senza Glutine"],
        isAvailable: true,
        isFeatured: false,
      },
      {
        name: "Tagliata di Manzo",
        description: "Controfiletto alla griglia servito con rucola selvatica, scaglie di Grana Padano e riduzione di balsamico di Modena",
        price: 22.00,
        categoryId: catMap["secondi"],
        ingredients: ["Controfiletto di Fassona", "Rucola", "Grana Padano", "Aceto balsamico", "Olio EVO"],
        allergens: ["lattosio"],
        dietaryTags: ["Senza Glutine"],
        isAvailable: true,
        isFeatured: true,
      },
      {
        name: "Burger Be Kind",
        description: "Hamburger artigianale da 180g con cheddar stagionato, bacon croccante, salsa Be Kind segreta e patatine fritte dorate",
        price: 15.00,
        categoryId: catMap["secondi"],
        ingredients: ["Manzo Angus 180g", "Cheddar", "Bacon", "Salsa speciale", "Lattuga", "Pomodoro", "Cipolla caramellata", "Brioche"],
        allergens: ["glutine", "lattosio", "uova"],
        dietaryTags: [],
        isAvailable: true,
        isFeatured: false,
      },
      {
        name: "Insalata Mista di Stagione",
        description: "Mix di foglie fresche di stagione con pomodorini, cetriolo e vinaigrette al limone",
        price: 5.00,
        categoryId: catMap["contorni"],
        ingredients: ["Insalata mista", "Pomodorini", "Cetriolo", "Vinaigrette"],
        allergens: [],
        dietaryTags: ["Vegan", "Vegetariano", "Senza Glutine"],
        isAvailable: true,
        isFeatured: false,
      },
      {
        name: "Patate al Forno con Rosmarino",
        description: "Patate dorate al forno con rosmarino fresco, aglio e olio extravergine d'oliva",
        price: 6.00,
        categoryId: catMap["contorni"],
        ingredients: ["Patate", "Rosmarino", "Aglio", "Olio EVO", "Sale"],
        allergens: [],
        dietaryTags: ["Vegan", "Vegetariano", "Senza Glutine"],
        isAvailable: true,
        isFeatured: false,
      },
      {
        name: "Verdure Grigliate",
        description: "Selezione di zucchine, melanzane, peperoni e carote alla griglia con olio e erbe aromatiche",
        price: 7.00,
        categoryId: catMap["contorni"],
        ingredients: ["Zucchine", "Melanzane", "Peperoni", "Carote", "Olio EVO", "Erbe miste"],
        allergens: [],
        dietaryTags: ["Vegan", "Vegetariano", "Senza Glutine"],
        isAvailable: true,
        isFeatured: false,
      },
      {
        name: "Tiramisù Classico",
        description: "Il nostro tiramisù della tradizione: mascarpone fresco, savoiardi imbevuti nel caffè espresso e cacao amaro",
        price: 7.50,
        categoryId: catMap["dolci"],
        ingredients: ["Mascarpone", "Savoiardi", "Caffè espresso", "Uova", "Zucchero", "Cacao amaro"],
        allergens: ["glutine", "lattosio", "uova"],
        dietaryTags: ["Vegetariano"],
        isAvailable: true,
        isFeatured: true,
      },
      {
        name: "Cheesecake ai Frutti di Bosco",
        description: "Base croccante di biscotto con crema cheesecake vellutata e coulis di frutti di bosco freschi",
        price: 8.00,
        categoryId: catMap["dolci"],
        ingredients: ["Biscotti", "Burro", "Formaggio spalmabile", "Panna", "Frutti di bosco", "Zucchero"],
        allergens: ["glutine", "lattosio", "uova"],
        dietaryTags: ["Vegetariano"],
        isAvailable: true,
        isFeatured: false,
      },
      {
        name: "Acqua Naturale / Frizzante",
        description: "Acqua minerale delle Marche, naturale o frizzante — 75cl",
        price: 2.50,
        categoryId: catMap["bevande"],
        ingredients: ["Acqua minerale"],
        allergens: [],
        dietaryTags: ["Vegan", "Vegetariano", "Senza Glutine"],
        isAvailable: true,
        isFeatured: false,
      },
      {
        name: "Coca-Cola / Coca-Cola Zero",
        description: "La classica bibita rinfrescante o versione senza zucchero — lattina 33cl",
        price: 3.00,
        categoryId: catMap["bevande"],
        ingredients: ["Bevanda gassata"],
        allergens: [],
        dietaryTags: ["Vegetariano"],
        isAvailable: true,
        isFeatured: false,
      },
      {
        name: "Calice di Vino della Casa",
        description: "Selezione del sommelier tra i migliori vini delle Marche — rosso o bianco",
        price: 5.00,
        categoryId: catMap["bevande"],
        ingredients: ["Vino rosso o bianco delle Marche"],
        allergens: ["solfiti"],
        dietaryTags: ["Vegan", "Vegetariano"],
        isAvailable: true,
        isFeatured: false,
      },
    ]);

    // Product Categories
    const productCats = await db.insert(productCategoriesTable).values([
      { name: "Abbigliamento", slug: "abbigliamento" },
      { name: "Accessori", slug: "accessori" },
      { name: "Food & Beverage", slug: "food-beverage" },
      { name: "Gift Card", slug: "gift-card" },
      { name: "Merchandise", slug: "merchandise" },
    ]).returning();

    const pCatMap: Record<string, number> = {};
    for (const c of productCats) pCatMap[c.slug] = c.id;

    // Products
    await db.insert(productsTable).values([
      {
        name: "T-Shirt Be Kind Classic",
        description: "T-shirt unisex in cotone organico certificato con logo Be Kind ricamato sul petto. Confortevole e sostenibile.",
        price: 29.90,
        categoryId: pCatMap["abbigliamento"],
        isAvailable: true,
        isFeatured: true,
        isNewArrival: false,
        variants: [
          { type: "Taglia", value: "S" },
          { type: "Taglia", value: "M" },
          { type: "Taglia", value: "L" },
          { type: "Taglia", value: "XL" },
        ],
      },
      {
        name: "Felpa Be Kind Hoodie",
        description: "Felpa con cappuccio in cotone felpato premium con logo Be Kind stampato. Calda e avvolgente per ogni stagione.",
        price: 59.90,
        categoryId: pCatMap["abbigliamento"],
        isAvailable: true,
        isFeatured: true,
        isNewArrival: true,
        variants: [
          { type: "Taglia", value: "S" },
          { type: "Taglia", value: "M" },
          { type: "Taglia", value: "L" },
          { type: "Taglia", value: "XL" },
          { type: "Colore", value: "Nero" },
          { type: "Colore", value: "Beige" },
        ],
      },
      {
        name: "Tote Bag Be Kind",
        description: "Borsa shopper in tela 100% cotone naturale non sbiancato. Capiente, resistente e ecologica.",
        price: 15.00,
        categoryId: pCatMap["accessori"],
        isAvailable: true,
        isFeatured: false,
        isNewArrival: true,
        variants: [],
      },
      {
        name: "Cappellino Be Kind",
        description: "Cappellino baseball con visiera e logo Be Kind ricamato. Regolabile con chiusura snap-back.",
        price: 22.00,
        categoryId: pCatMap["accessori"],
        isAvailable: true,
        isFeatured: false,
        isNewArrival: false,
        variants: [
          { type: "Colore", value: "Nero" },
          { type: "Colore", value: "Bianco" },
          { type: "Colore", value: "Verde" },
        ],
      },
      {
        name: "Olio EVO Be Kind",
        description: "Olio extravergine d'oliva 500ml della nostra produzione locale nelle Marche. Raccolto a mano, prima spremitura a freddo.",
        price: 12.00,
        categoryId: pCatMap["food-beverage"],
        isAvailable: true,
        isFeatured: true,
        isNewArrival: false,
        variants: [],
      },
      {
        name: "Miele Millefiori Be Kind",
        description: "Miele artigianale 250g prodotto dai nostri apicoltori locali. Raccolto nelle campagne marchigiane.",
        price: 9.50,
        categoryId: pCatMap["food-beverage"],
        isAvailable: true,
        isFeatured: false,
        isNewArrival: false,
        variants: [],
      },
      {
        name: "Gift Card Be Kind €25",
        description: "Carta regalo Be Kind da €25. Valida per tutti i servizi: ristorante, shop, eventi. Nessuna scadenza.",
        price: 25.00,
        categoryId: pCatMap["gift-card"],
        isAvailable: true,
        isFeatured: false,
        isNewArrival: false,
        variants: [],
      },
      {
        name: "Gift Card Be Kind €50",
        description: "Carta regalo Be Kind da €50. Il regalo perfetto per chi ama il buon cibo e le esperienze autentiche.",
        price: 50.00,
        categoryId: pCatMap["gift-card"],
        isAvailable: true,
        isFeatured: true,
        isNewArrival: false,
        variants: [],
      },
    ]);

    // Events
    await db.insert(eventsTable).values([
      {
        title: "Workshop: Pasta Fresca Fatta in Casa",
        description: "Impara l'arte della pasta fresca con lo Chef Marco. Dalla sfoglia ai tortellini: un viaggio nella tradizione culinaria italiana. Al termine del workshop degusterai i tuoi capolavori.",
        date: "2026-04-15",
        startTime: "10:00",
        endTime: "13:00",
        location: "Cucina Be Kind, Via Roma 12, Ancona",
        category: "Cucina",
        price: 35.00,
        maxParticipants: 15,
        isFree: false,
      },
      {
        title: "Degustazione Vini Locali",
        description: "Scopri i migliori vini delle Marche con il nostro sommelier certificato. Vermentino, Lacrima di Morro d'Alba, Rosso Conero: un viaggio tra i profumi e i sapori del territorio.",
        date: "2026-04-21",
        startTime: "19:00",
        endTime: "21:00",
        location: "Sala Eventi Be Kind, Via Roma 12, Ancona",
        category: "Degustazione",
        price: 25.00,
        maxParticipants: 20,
        isFree: false,
      },
      {
        title: "Be Kind Music Night",
        description: "Una serata di live music con DJ set e aperitivo gourmet incluso. La terrazza di Be Kind si trasforma in un palco aperto alle stelle. Prenotazione obbligatoria.",
        date: "2026-04-29",
        startTime: "21:00",
        endTime: "00:00",
        location: "Terrazza Be Kind, Via Roma 12, Ancona",
        category: "Musica",
        price: 15.00,
        maxParticipants: 50,
        isFree: false,
      },
      {
        title: "Yoga & Brunch",
        description: "Inizia la domenica con una sessione di yoga per tutti i livelli nel nostro giardino, seguita da un brunch salutare e rigenerante preparato con prodotti bio locali.",
        date: "2026-05-06",
        startTime: "09:00",
        endTime: "12:00",
        location: "Giardino Be Kind, Via Roma 12, Ancona",
        category: "Benessere",
        price: 30.00,
        maxParticipants: 25,
        isFree: false,
      },
      {
        title: "Community Day: Pulizia Spiagge",
        description: "Unisciti a noi per una giornata di volontariato ambientale sulla splendida spiaggia di Portonovo. Be Kind si prende cura del territorio. Pranzo offerto da Be Kind a tutti i partecipanti.",
        date: "2026-05-12",
        startTime: "09:00",
        endTime: "13:00",
        location: "Spiaggia di Portonovo, Ancona",
        category: "Community",
        price: 0,
        maxParticipants: 40,
        isFree: true,
      },
    ]);

    logger.info("Database seeded successfully");
  } catch (error) {
    logger.error({ error }, "Error seeding database");
  }
}
